Exercises

Using the repo setup directions, setup a new local and remote repository named statistics-exercises. The local version of your repo should live inside of ~/codeup-data-science. This repo should be named statistics-exercises

Do your work for this exercise in either a python file named simulation.py or a jupyter notebook named simulation.ipynb.

In [1]:
import numpy as np
import pandas as pd
np.random.seed(29)

1. How likely is it that you roll doubles when rolling two dice?
    - 0.1633

In [13]:
#set up options for roll. assume 6 sided
#do tests where two dice are rolled 
#figure out how many of the tests came out with both dice being the same. --> make note of how to access list members inside of numpy array

In [40]:
rolls1 = np.random.choice(['1', '2', '3', '4', '5', '6'], size=(10_000, 2)) 

In [41]:
doubles = rolls1[:,0] == rolls1[:,1]

In [42]:
(doubles == True).mean()

0.1633

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?
   - 0.2216

In [43]:
#set up options for the flips
#do the flips and assign to variable
flips1 = np.random.choice(['H', 'T'], size=(10_000, 8) )

In [50]:
#count number of heads in each set of 8 flips (the rows) and assign to variable
head_count = (flips1 == 'H').sum(axis=1)

In [52]:
#check head_count rows for rows with head_count of 3
#use mean to figure out the percetange of all the flips 
(head_count == 3).mean()

0.2216

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

0.2517

In [55]:
#set up choice options with probabilities for each
billboards = np.random.choice(['wd', 'ds'], size=(10_000, 2), p=[.75, .25])

In [68]:
#find and total where both billboards (a row) are 'ds' (data science)
(billboards == ('ds', 'ds')).sum()

5034

In [69]:
#calculate proportion of total simulations (1000) that meet the criteria
(billboards == ('ds', 'ds')).mean()

0.2517

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values
    - 0.9103

In [84]:
#generate random daily poptart values --> just use the size keyword. 
def daily_poptart():
    return np.random.normal(loc=3, scale=1.5)
#generate 5 random poptart values to get one week of random poptarts
weekly_poptarts = [daily_poptart() for n in range(4)]
weekly_poptarts

In [92]:
#generate array with weeks(rows) of 4 days (mon-thur) worth of poptart purchases
weekly_poptarts = np.random.normal(loc=3, scale=1.5, size=(10_000, 4))

In [95]:
weekly_poptarts

array([[2.42906507, 2.46387183, 4.41413546, 3.2832918 ],
       [4.22070906, 2.83954935, 1.77150541, 4.75107998],
       [2.53867692, 3.39561915, 1.14046151, 1.30644852],
       ...,
       [0.24320391, 3.43394498, 3.03830732, 2.39103099],
       [5.42987724, 1.85827302, 2.23060552, 0.86674667],
       [3.71389468, 5.31258567, 2.21096157, 2.75875431]])

In [94]:
#sum each week of poptars, and then check which weeks (mon-thur) have totals at or below 16
weekly_poptarts.sum(axis=1)

array([12.59036416, 13.58284379,  8.38120609, ...,  9.1064872 ,
       10.38550244, 13.99619623])

In [101]:
#do the same as above but use np.ceil to round up. better to over estimate poptart purchases than under in order to manage expectations. let's assign it to a variable for clarity. 

cumulative_poptarts = np.ceil(weekly_poptarts.sum(axis=1)).astype(int)

In [104]:
#take average (mean) of the number of weeks in which 16 or less poptarts were purchased from mon-thurs
(cumulative_poptarts <= 16).mean() 

0.9103

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.

In [154]:
#generate random m and w heights
heights = np.random.normal(loc=(178, 170), scale=(8,6), size=(10_000, 2)) # --> can use two means and sd's for concurrent simulations


In [160]:
heights

array([[175.65484189, 175.81856708],
       [186.28752337, 166.81528575],
       [173.39343277, 154.27573041],
       ...,
       [178.92882615, 170.42311659],
       [171.82907847, 167.88825143],
       [178.48794764, 173.61360174]])

If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
    - 0.2091

In [159]:
(heights[:,0] < heights[:,1]).mean()

0.2091

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.
What are the odds that after having 50 students download anaconda, no one has an installation issue? 
- .81877

100 students?
- .66817

In [173]:
#this is a coin flip with weighted odds
fifty_installs = np.random.choice(['success', 'fail'], size=(100_000, 50), p=[.996, .004])

In [174]:
has_fails = (fifty_installs == 'fail').sum(axis=1)

In [177]:
(has_fails == 0).mean()

0.81877

In [178]:
hundred_installs = np.random.choice(['success', 'fail'], size=(100_000, 100), p=[.996, .004])
fails = (hundred_installs == 'fail').sum(axis=1)
(fails == 0).mean()

0.66817

What is the probability that we observe an installation issue within the first 150 students that download anaconda?
- .44956

In [179]:
one_fifty_installs = np.random.choice(['success', 'fail'], size=(100_000, 150), p=[.996, .004])
fails_two = (one_fifty_installs == 'fail').sum(axis=1)
(fails_two > 0).mean()

0.44956

How likely is it that 450 students all download anaconda without an issue?
- .16356

In [180]:
four_fifty_installs = np.random.choice(['success', 'fail'], size=(100_000, 450), p=[.996, .004])
fails_three = (four_fifty_installs == 'fail').sum(axis=1)
(fails_three == 0).mean()

0.16356

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
- 0.02629

In [190]:
#a batch 3 binary choices - truck/no_truck --> dont forget to add in the percentage weights
travis_park = np.random.choice(['truck', 'no_truck'], size=(100_000, 3), p=[.7, .3])

In [191]:
#count days within each interval (row) that a truck showed up
truck_days = (travis_park == 'truck').sum(axis=1)

In [192]:
#find average of intervals where no truck showed up
(truck_days == 0).mean()

0.02629

How likely is it that a food truck will show up sometime this week?
- .9998

In [193]:
weekly_trucks = np.random.choice(['truck', 'no_truck'], size=(100_000, 7), p=[.7, .3])

In [196]:
days_with_truck = (weekly_trucks == 'truck').sum(axis=1)

In [197]:
(days_with_truck > 0).mean()

0.9998

If 23 people are in the same room, what are the odds that two of them share a birthday?
- .3639

What if it's 20 people? 
- .3232

40?
- .2626

In [211]:
twenty_three_bdays = np.random.choice(range(365), size=(10_000, 23))

In [219]:
twenty_three_df = pd.DataFrame(twenty_three_bdays)

In [227]:
(twenty_three_df.nunique(axis=1) == 22).mean()

0.3639

In [231]:
twenty_people = np.random.choice(range(365), size=(10_000, 20))
twenty_df = pd.DataFrame(twenty_people)
(twenty_df.nunique(axis=1) == 19).mean()

0.3232

In [232]:
forty_people_df = pd.DataFrame(np.random.choice(range(365), size=(10_000, 40)))
(forty_people_df.nunique(axis=1) == 39).mean()

0.2626